package com.github.sylordis.tools.csvreorganiser.model.constants;

/**
 * This class contains all constants related to messages.
 *
 * @author sylordis
 * @since 1.1
 *
 */
public final class MessagesConstants {

	/**
	 * Comment written as first line of generated reorganised files.
	 */
	public static final String TARGET_COMMENT = "# Generated by CSV reorganiser (%DATE)";

	/**
	 * Private constructor to prevent instantiation.
	 */
	private MessagesConstants() {
		// Nothing to see here
	}

}
