package com.github.sylordis.csvreorganiser.model.constants;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * This class contains all constants related to messages.
 *
 * @author sylordis
 *
 */
public final class MessagesConstants {

	/**
	 * Comment written as first line of generated reorganised files.
	 */
	public static final String TARGET_COMMENT = "# Generated by CSV reorganiser [%s] (%s)";
	/**
	 * Default statement for empty documentation.
	 */
	public static final String DOCUMENTATION_NOT_PROVIDED = "Documentation not provided";

	/**
	 * Gets the full message for the header comment, with date as current time.
	 * 
	 * @param engine
	 * @return
	 */
	public static final String getTargetComment(String engine) {
		return getTargetComment(DateTimeFormatter.ISO_LOCAL_DATE_TIME.format(LocalDateTime.now()), engine);
	}

	/**
	 * Gets the full message for the header comment, specifying all parameters. <br/>
	 * <br/>
	 * This method is mostly here for testing purposes.
	 * 
	 * @param date
	 * @param engine
	 * @return
	 */
	public static final String getTargetComment(String date, String engine) {
		return String.format(TARGET_COMMENT, engine, date);
	}

	/**
	 * Private constructor to prevent instantiation.
	 */
	private MessagesConstants() {
		// Nothing to see here
	}

}
