package com.github.sylordis.csvreorganiser.model.constants;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * This class contains all constants related to messages.
 *
 * @author sylordis
 *
 */
public final class MessagesConstants {

	/**
	 * Comment written as first line of generated reorganised files.
	 */
	public static final String TARGET_COMMENT = "# Generated by CSV reorganiser (%s) (%s)";

	/**
	 * Gets the full message for the header comment.
	 * @param engine
	 * @return
	 */
	public static final String getTargetComment(String engine) {
		return String.format(TARGET_COMMENT, DateTimeFormatter.ISO_LOCAL_DATE_TIME.format(LocalDateTime.now()), engine);
	}

	/**
	 * Private constructor to prevent instantiation.
	 */
	private MessagesConstants() {
		// Nothing to see here
	}

}
